WDI-Workspace/Week-05/Day-03/boats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'boats/' => 'boats#index', as: :boats
  get 'boats/:id' => 'boats#show', as: :boat
  delete 'boats/:id' => 'boats#destroy', as: :burn_it
end

WDI-Workspace/Week-05/Day-03/boats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WDI-Workspace/Week-05/Day-03/boats/app/models/boat.rb
class Boat < ApplicationRecord
end

WDI-Workspace/Week-05/Day-03/boats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

WDI-Workspace/Week-05/Day-03/boats/app/controllers/boats_controller.rb
class BoatsController < ApplicationController
	
	def index
		@boats = Boat.all
	end

	def show
		@boats = Boat.find(params[:id])
	end

	def destroy
		@boat = Boat.find(params[:id])
		@boat.delete
		redirect_to boats_path
	end
end

WDI-Workspace/Week-05/Day-03/boats/app/helpers/application_helper.rb
module ApplicationHelper
end

WDI-Workspace/Week-05/Day-03/boats/app/views/boats/index.html.erb
<h1>Boats and hoes!!!</h1>

<ul>
	<% @boats.each do |boat| %>
		<li>Name of Boat: <%= boat.title %> 
		<%= link_to('Check out boat', boat_path(boat)) %>
		<button style="text-decoration: none;"><%= link_to('X', burn_it_path(boat), method: :delete) %></button>
		</li>
	<% end %>
</ul>

WDI-Workspace/Week-05/Day-03/boats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>